<<filename:l:app/design/frontend/base/default/template/[module]:"example">>
<<var:n:module prefix => [Prefix]>>
<<var:l:module prefix => [prefix]>>
<<var:c:module name => [Module]>>
<<var:l:module name => [module]>>
<<var:l:code pool => [codepool]>>

<?php 
/*
 * grab config settings from demoblock.php to do stuff with, or just do stuff
 * 
 */


// grab all settings
$adminsettings = $this->getStuff();

//or use a helper if you want
$fromhelper = $this->helper('[module]')->getConfig();

// grab specific settings
$myoptions = $fromhelper['option_group'];
$mysettings = $fromhelper['anothersettings_group'];

?>


<div>
    <h1>[Prefix] [Module] Example PHTML template</h1>
    <p>
        this is output by:<br />
        app/design/frontend/default/default/template/[module]/example.phtml
    </p>
    <p>
        This is one way you can output a specific value or setting<br />
        <h2><?php echo $adminsettings; ?></h2>
        <span>^^^^  this value  ^^^^  can be entered/changed in System >> Configuration >> [Module] Settings</span><br />
        also note that this stuff is stored in the database under core_config_data table, all the way at the end...
    </p>
</div>


